### ISSUE TITLE
get-metadata: add "Refs:" in metadata

### ISSUE THREAD

**Issue by vsemozhetbyt** [nodejs/node-core-utils#117]
Example: https://github.com/nodejs/node/pull/17107

IIRC, nodejs/node-review [adds this data](https://github.com/nodejs/node-review/search?utf8=%E2%9C%93&q=Refs&type=).

**Comment by Tiriel** [comment]
Strange, this feature is already implemented and is supposed to work, but I can't get Refs in metadata either. 
Unit tests are even working and properly returning Refs. I'll investigate, if someone doesn't beat me to it.

**Comment by joyeecheung** [comment]
node-review doesn't add that refs, actually.

<img width="405" alt="screen shot 2017-11-19 at 12 36 44 am" src="https://user-images.githubusercontent.com/4299420/32982590-c0de4904-ccc1-11e7-9e06-511b1cc77e2b.png">

The link parser code is largely borrowed from node-review. It currently only take urls that are `a.issue-link` i.e. github issues/PRs

**Comment by joyeecheung** [comment]
@Tiriel Did you have a chance to look into this?

**Comment by Tiriel** [comment]
@joyeecheung Not yet, had a pretty busy week. Putting it on my schedule for tonight!

**Comment by cPhost** [comment]
The reason `Refs` is not being inserted to metadata because of
https://github.com/nodejs/node-core-utils/blob/edd107a706571bb69937f6ee02b74ff6b12c13f1/lib/links.js#L48

The query selector at line 48 `a.issue-link` returns undefined because github no longer uses `.issue-link` class and thats the reason the tests are passing but the feature is not working.

Way to fix this issue is just to remove `.issue-link` . and remove the unnecessary attributes form test except `href` just to make the test more readable.

\cc @joyeecheung @Tiriel

**Comment by Tiriel** [comment]
Still looking for a propoer way to parse the links recursively, I'm on it ;)

**Comment by joyeecheung** [comment]
@cPhost SGTM

**Comment by Tiriel** [comment]
Don't know what I did last night but I was way too far... Opening a PR. Removing the class was all that was needed it seems. Tests OK and example given OK too.
