### ISSUE TITLE
CHANGELOG?

### ISSUE THREAD

**Issue by alopezsanchez** [nodejs/node-core-utils#118]
With the project growing everyday... Don't we should include a `CHANGELOG.md`?

**Comment by targos** [comment]
+1. What about using [standard-version](https://github.com/conventional-changelog/standard-version) to generate it automatically? We would just have to choose a style for commit messages.

**Comment by Tiriel** [comment]
Definitely +1!

zlthough I was going to suggest using [changelog-maker](https://github.com/nodejs/changelog-maker) :smile:

**Comment by joyeecheung** [comment]
+1 to changelog-maker for dog-fooding

**Comment by BridgeAR** [comment]
As this project is actually not that big, I personally prefer [standard-version](https://github.com/conventional-changelog/standard-version) because we do not have to think about labeling patch / minor / major and I prefer the standard message style that would come with it.
But either would be fine out of my perspective.

**Comment by cPhost** [comment]
We think we now use github's releases to include highlights and changelogs i thinks that good enough when creating new release instead of having to commit a changelog.

So this could be closed right?

**Comment by joyeecheung** [comment]
> So this could be closed right?

SGTM.

BTW I just use 

```
git log --pretty=format:"- %s" <old-tag>...<new-tag>~1
```

to generate the list.

**Comment by cPhost** [comment]
For the last release i edited on github was just for trying it out it did not include any formal changelog :), but now it looks it works..
