### ISSUE TITLE
still does not detect some non-author committers

### ISSUE THREAD

**Issue by joyeecheung** [nodejs/node-core-utils#150]
See https://github.com/nodejs/node/pull/17705

**Comment by joyeecheung** [comment]
It is kind of weird, the committer and the author actually use the same email, and `authoredByCommitter` is true here, still GitHub UI does not recognize that...

**Comment by cPhost** [comment]
Ah, it might be because the remove the email in the settings.

**Comment by cPhost** [comment]
@joyeecheung the reason i think it failes is because of this here 
https://github.com/nodejs/node-core-utils/blob/e76076d27173bb018ff52ee8ea2740ffc74bc033/lib/pr_checker.js#L282-L286D

I don't think `email` field exists on `author`. Can you tell me exactly what the purpose was here?

(I do think they have a GitHub email provied by github for this purposes of making email private)

**Comment by joyeecheung** [comment]
@cPhost That is assigned here

https://github.com/nodejs/node-core-utils/blob/e76076d27173bb018ff52ee8ea2740ffc74bc033/lib/pr_data.js#L84-L86

**Comment by cPhost** [comment]
That seems correct. And also you can do this to save you some more work.
```graphql
author {
  ... on User {
     email,
     name
  }
}
```
