### ISSUE TITLE
new tool: git hooks (pre-push, pre-commit)

### ISSUE THREAD

**Issue by joyeecheung** [nodejs/node-core-utils#160]
1. Should be a symlink in `.git/hooks/pre-push`
2. Use the remote and branch config that we have, stop users from pushing invalid commits, especially merge commits.

**Comment by cPhost** [comment]
I worked on creating pre-push hook before, we can surely implement it. Alternatively we can also have `pre-commit` that runs linter only if the user wants.

**Comment by alopezsanchez** [comment]
Questions:
* This hook will be only for node-core-utils project, it will be a tool for collaborators of all Node.js projects, or a tool for any contributor?
* Language of the script? Bash, Node...?

I can work of it if you don't have any inconveniences.

**Comment by joyeecheung** [comment]
> This hook will be only for node-core-utils project, it will be a tool for collaborators of all Node.js projects, or a tool for any contributor?

For node core, I think. It's just a script that people can symlink to, we can ask the users if they want to symlink that during the npm `post-install` hook. People can also symlink to other repos if they want.

> Language of the script? Bash, Node...?

Well I guess it'll need to read the `.ncu/config` at some point, which is JSON, so it'll be easier to write that in Node

**Comment by cPhost** [comment]
> Language of the script? Bash, Node...?

Yep, agreed that it should be in node. But the symlinked script must be in bash, since windows also supports bash in git hooks.

And furthermore in the `.git/hooks` folder you need to make sure that you remove the `.sample` file for the hook since sometimes this causes the hook to not run.

Lastly, the hook should output info about using `--no-verify` flag to skip this hook.
