### ISSUE TITLE
cli tests flake on appveyor

### ISSUE THREAD

**Issue by priyankp10** [nodejs/node-core-utils#174]
It seems like we have cli test flake on appveyor ci.
https://ci.appveyor.com/project/joyeecheung/node-core-utils/build/318.master#L192

**Comment by joyeecheung** [comment]
I thought I fixed that in https://github.com/nodejs/node-core-utils/pull/167 , guess I just got lucky and the test didn't fail...as I said in https://github.com/nodejs/node-core-utils/pull/167 , they are basically testing the behavior of ora - we should at least stub `cli.spinner` instead of depending on how ora manipulates it (although the tests would still be pretty superfluous that way, e.g. testing `cli.startSpinner` has done `this.spinner.text = text` and `this.spinner.start()` by testing `assert.strictEqual(cli.spinner.text, text)` and `assert(cli.spinner.start.calledOnce())`

**Comment by cPhost** [comment]
I think its does make sense to remove code testing ora, which works on windows, and not test our side of functionality provided.

@alopezsanchez would you be up for this, since you wrote the tests?

**Comment by alopezsanchez** [comment]
Yes, no problem. Let me take a look!

**Comment by cPhost** [comment]
Updating ora to `1.4.0` also causes test failures in macos not just windows and they are not flaky so we that might also be use while tracing this.

**Comment by joyeecheung** [comment]
We have removed tests against the spinner so this can be closed.
