### ISSUE TITLE
Weird weekend detection

### ISSUE THREAD

**Issue by targos** [nodejs/node-core-utils#215]
`git node metadata 19203`

```
...
ℹ  This PR was created on Wed Mar 07 2018 (weekend in UTC)
⚠  5 hours left to land
```

**Comment by GithubGoldMiner** [comment]
Hi, @targos I think it is actually caused by this line:
https://github.com/nodejs/node-core-utils/blob/b94a6086b9452776c8d38053cd64f7d781cc3d43/lib/pr_checker.js#L134

In stead of using `utcDay`, we should use `createTime` to show whether that PR was created during weekends. 

@cPhost I can create a PR to fix this bug if you want. I think the test cases also failed.

**Comment by cPhost** [comment]
@GithubGoldMiner go for it :)
