### ISSUE TITLE
`git node v8 backport` aborts on merge conflict

### ISSUE THREAD

**Issue by hashseed** [nodejs/node-core-utils#303]
`git node v8 backport` attempts at some point to do a `git apply -3`, which fails often. The `-3` doesn't help since Node's copy of V8 doesn't have a git history.

How about not aborting, but wait for the user to fix the conflicts and `git add` the fixes and then continue?

**Comment by targos** [comment]
+1000 if you know how to do that! I was not able to get conflict markers with `git apply` when I developed the command.

**Comment by joyeecheung** [comment]
I think the thing to implement is more like to have a way to persist the failure and then be able to restart from here once the user fixes the conflict?

https://github.com/nodejs/node-core-utils/blob/092cbe5d997eb565e967eed5d9f44beb0f958dde/lib/update-v8/backport.js#L12

`git node land` is able to do that by persisting states to `.ncu/land` and always reading this file to understand the previous state so that users can `git node land --continue` all the way down while fixing errors

**Comment by targos** [comment]
The real problem is that there is no conflict to fix. The patch fails and that's all. No files are modified

**Comment by joyeecheung** [comment]
@targos One way to tackle that is to use `git apply --reject`, and prompt the user to use [wiggle](https://linux.die.net/man/1/wiggle) on the `.rej` files, though that cannot guarantee to work either (I guess it's better than outright failure?) Then when the conflicts are fixed, read some persisted state from disk to bake the commit message and so on.

**Comment by hashseed** [comment]
I made an attempt to solve this: use `patch -p1 --merge --no-backup-if-mismatch` so that we get conflict markers in the files, and then prompt the user to continue once conflicts are resolved.
