### ISSUE TITLE
git-node does not accept current github token format

### ISSUE THREAD

**Issue by mhdawson** [nodejs/node-core-utils#617]
Looks to me like https://github.com/nodejs/node-core-utils/pull/613 does not allow the "new" token format from github which start tokens with a string like `ghp_` to be accepted.

@Trott wondering what the motivation for this addition was:

  if (!/^[0-9a-f]+$/.test(token)) {
    errorExit(`token must be lowercase hexadecimal, received ${token}`);
  }

**Comment by Trott** [comment]
> Looks to me like #613 does not allow the "new" token format from github which start tokens with a string like `ghp_` to be accepted.
> 
> @Trott wondering what the motivation for this addition was:
> 
> if (!/^[0-9a-f]+$/.test(token)) { errorExit(`token must be lowercase hexadecimal, received ${token}`); }

It was a fix to this line that it replaced:

```javascript
assert(typeof token === 'string' && /^[0-9a-f]*/.test(token));
```

That line is broken because it matches anything. (The `*` means "zero or more characters, so that regular expression will match any string whatsoever, including an empty string.)

It should very easy to fix the validation so that it allows for `_` and to add a test for the new token format. I'll do that in a few hours when I'm in front of a computer, unless someone else beats me to it.

Another possibility is to remove validation entirely, but I would prefer not.

**Comment by Trott** [comment]
Fix is in https://github.com/nodejs/node-core-utils/pull/618
