### ISSUE TITLE
Todo: Skip the wait check for specific PRs

### ISSUE THREAD

**Issue by Tiriel** [nodejs/node-core-utils#94]
Hey!

Related to #89 , and as seen in [#92(comment)](https://github.com/joyeecheung/node-core-utils/pull/92#issuecomment-342593313):
* [ ] check for labels `doc` and `test`
* [ ] check for a max number of files

Question: what is the ideal number of files? I would go for three, but I'm not an expert...

**Comment by alopezsanchez** [comment]
Hello!

It's not possible to retrieve files/diffs at the moment with GraphQL API (https://github.com/joyeecheung/node-core-utils/issues/68#issuecomment-342031633), so I'm afraid we have to wait for the second point.

But I can do the first one if there are no incoveniences.

**Comment by apapirovski** [comment]
I would probably suggest holding off. I feel like this is something that needs to be discussed within Node.js itself a bit...

IMO a lot of this could be simplified by setting a 24 hour limit (instead of 48 hours) on doc, test & code-and-learn changes. Then it can stop being so arbitrary.

/cc @addaleax, @joyeecheung

**Comment by alopezsanchez** [comment]
Oh, okay @apapirovski, I didn't know that. Thank you!

**Comment by vsemozhetbyt** [comment]
New rules landed: https://github.com/nodejs/node/pull/17056
In PRs like [this](https://github.com/nodejs/node/pull/17107) the warning may need to be suppressed.

**Comment by joyeecheung** [comment]
Fixed, closing
